#   This file .yml allows us to give the specific instructions to docker-compose 
#   on how to manage these different services (images)
version: "3"

# Definition of the different services (images) to use 
services:
    nginx:
        container_name: nginx # name of the container
        build:          ./requirements/nginx/
        image:          nginx:inception
        env_file:       .env # defines the optional file containing the environment
        networks:
            - inception
        ports:          # port in use
            - "443:443"
        restart:        on-failure  #allows the container to restart in case of crash
        volumes:
            - wordpress-data:/var/www/html/
        depends_on:
            - wordpress
    mariadb:
        container_name: mariadb
        build:          ./requirements/mariadb/
        image:          mariadb:inception
        env_file:       .env
        networks:
            - inception
        restart:        on-failure
        volumes:
            - mariadb-data:/var/lib/mysql/
    wordpress:
        container_name: wordpress
        build:          ./requirements/wordpress/
        image:          wordpress:inception
        env_file:       .env
        networks:
            - inception
        restart:        on-failure
        volumes:    # Path where our wordpress files are present
            - wordpress-data:/var/www/html/
        depends_on:
            - mariadb

networks:
    inception:
        name:   inception
        driver: bridge

volumes:
  mariadb-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${DATA_PATH}/mariadb-data
  wordpress-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${DATA_PATH}/wordpress-data

