#   This file .yml allows us to give the specific instructions to docker-compose 
#   on how to manage these different services (images)
version: "3.5"

# Definition of the different services (images) to use 
services:
    nginx:
        container_name: nginx # name of the container
        build:          requirements/nginx/
        restart:        always #allows the container to restart in case of crash
        env_file:       .env # defines the optional file containing the environment
        networks:
            - inception
        ports:          # port in use
            - "443:443"
        volumes:
            - wordpress-data:/var/www/html/
        depends_on:
            - wordpress

    mariadb:
        container_name: mariadb
        build:          requirements/mariadb/
        restart:        always
        env_file:       .env
        networks:
            - inception
        volumes:
            - mariadb-data:/var/lib/mysql/

    wordpress:
        container_name: wordpress
        build:          requirements/wordpress/
        restart:        always
        env_file:       .env
        networks:
            - inception
        volumes:    # Path where our wordpress files are present
            - wordpress-data:/var/www/html/
        depends_on:
            - mariadb

# NETWORK
networks:
    inception:
        name:   inception
        driver: bridge

# VOLUMES
volumes:
  mariadb-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/mflores-/data/mariadb

  wordpress-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/mflores-/data/wordpress
